# Generated by Django 5.2.16 on 2026-07-08 14:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("icv_sitemaps", "0001_initial"),
        ("icv_sitemaps", "0002_alter_sitemapsection_model_path_and_more"),
        ("icv_sitemaps", "0003_alter_robotsrule_directive"),
        ("icv_sitemaps", "0004_redirectlog_redirectrule"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdsEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Leave blank for single-tenant use.",
                        max_length=200,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text='Advertising system domain, e.g. "google.com".',
                        max_length=200,
                    ),
                ),
                (
                    "publisher_id",
                    models.CharField(
                        help_text="Publisher account ID assigned by the advertising system.",
                        max_length=200,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[("DIRECT", "Direct"), ("RESELLER", "Reseller")],
                        help_text="Whether the seller is a direct publisher or a reseller.",
                        max_length=10,
                    ),
                ),
                (
                    "certification_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional TAG-ID certification authority ID.",
                        max_length=200,
                    ),
                ),
                (
                    "is_app_ads",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this entry belongs to app-ads.txt; otherwise ads.txt.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this entry is included when rendering the ads file.",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Optional comment for internal reference.",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "ads.txt entry",
                "verbose_name_plural": "ads.txt entries",
                "db_table": "icv_sitemaps_ads_entry",
                "ordering": ["domain", "publisher_id"],
            },
        ),
        migrations.CreateModel(
            name="SitemapSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Logical section name, e.g. "products" or "articles".',
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier for multi-tenant setups. Leave blank for single-tenant use.",
                        max_length=200,
                    ),
                ),
                (
                    "model_path",
                    models.CharField(
                        help_text='Django model in "app_label.ModelName" format, e.g. "catalog.Product".',
                        max_length=500,
                    ),
                ),
                (
                    "sitemap_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("news", "News"),
                        ],
                        default="standard",
                        help_text="Type of sitemap to generate for this section.",
                        max_length=20,
                    ),
                ),
                (
                    "changefreq",
                    models.CharField(
                        choices=[
                            ("always", "Always"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("never", "Never"),
                        ],
                        default="daily",
                        help_text="Default change frequency for URLs in this section.",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=1,
                        default="0.5",
                        help_text="Default URL priority for this section (0.0-1.0).",
                        max_digits=2,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this section is included in sitemap generation.",
                    ),
                ),
                (
                    "is_stale",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this section needs regeneration.",
                    ),
                ),
                (
                    "last_generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last successful generation run.",
                        null=True,
                    ),
                ),
                (
                    "url_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total URLs across all files for this section.",
                    ),
                ),
                (
                    "file_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of XML files generated for this section.",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Section-specific configuration overrides (JSON).",
                    ),
                ),
            ],
            options={
                "verbose_name": "sitemap section",
                "verbose_name_plural": "sitemap sections",
                "db_table": "icv_sitemaps_section",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_stale"],
                        name="icv_sm_sect_actv_stl_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("name", "tenant_id"), name="icv_sm_sect_name_tnt_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="SitemapGenerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("generate_section", "Generate section"),
                            ("generate_all", "Generate all"),
                            ("generate_index", "Generate index"),
                            ("ping", "Ping search engines"),
                        ],
                        help_text="Action type for this generation run.",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        help_text="Current status of this generation run.",
                        max_length=20,
                    ),
                ),
                (
                    "url_count",
                    models.PositiveIntegerField(default=0, help_text="Total URLs generated in this run."),
                ),
                (
                    "file_count",
                    models.PositiveIntegerField(default=0, help_text="Number of files written in this run."),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, help_text="Generation time in milliseconds."),
                ),
                (
                    "detail",
                    models.TextField(blank=True, help_text="Error message or summary for this run."),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Section that was generated. Null for a full-site regeneration run.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_logs",
                        to="icv_sitemaps.sitemapsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "sitemap generation log",
                "verbose_name_plural": "sitemap generation logs",
                "db_table": "icv_sitemaps_generation_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscoveryFileConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Leave blank for single-tenant use.",
                        max_length=200,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("llms_txt", "llms.txt"),
                            ("security_txt", "security.txt"),
                            ("humans_txt", "humans.txt"),
                        ],
                        help_text="The discovery file this record configures.",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Raw file content to serve at the file's canonical URL."),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this file is served when requested.",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last edited this configuration.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "discovery file configuration",
                "verbose_name_plural": "discovery file configurations",
                "db_table": "icv_sitemaps_discovery_config",
                "ordering": ["file_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("file_type", "tenant_id"),
                        name="icv_sm_disc_type_tnt_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SitemapFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="File sequence number within the section (0-based).",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        help_text='Path to the XML file in storage, e.g. "sitemaps/products-0.xml".',
                        max_length=500,
                    ),
                ),
                (
                    "url_count",
                    models.PositiveIntegerField(default=0, help_text="Number of URLs in this file."),
                ),
                (
                    "file_size_bytes",
                    models.PositiveIntegerField(default=0, help_text="Size of the generated XML file in bytes."),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of the file contents for change detection.",
                        max_length=64,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this file was generated."),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="The parent sitemap section that produced this file.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="icv_sitemaps.sitemapsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "sitemap file",
                "verbose_name_plural": "sitemap files",
                "db_table": "icv_sitemaps_file",
                "ordering": ["section", "sequence"],
                "constraints": [
                    models.UniqueConstraint(fields=("section", "sequence"), name="icv_sm_file_sect_seq_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="RobotsRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Leave blank for single-tenant use.",
                        max_length=200,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        default="*",
                        help_text='User agent string, e.g. "*", "Googlebot", or "GPTBot".',
                        max_length=200,
                    ),
                ),
                (
                    "directive",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("disallow", "Disallow"),
                            ("crawl-delay", "Crawl-delay"),
                            ("sitemap", "Sitemap"),
                            ("host", "Host"),
                        ],
                        help_text="Robots.txt directive, e.g. Allow, Disallow, or Crawl-delay.",
                        max_length=20,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        default="/",
                        help_text='URL path pattern, e.g. "/admin/", "/api/", or "/*.pdf$".',
                        max_length=500,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sort order within the user agent group (lower = first).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this rule is included when rendering robots.txt.",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Optional comment explaining the purpose of this rule.",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "robots.txt rule",
                "verbose_name_plural": "robots.txt rules",
                "db_table": "icv_sitemaps_robots_rule",
                "ordering": ["user_agent", "order"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "user_agent", "order"],
                        name="icv_sm_robots_tnt_ua_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RedirectLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.CharField(
                        help_text="Request path that returned 404.",
                        max_length=2000,
                        verbose_name="path",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Leave blank for single-tenant use.",
                        max_length=200,
                        verbose_name="tenant ID",
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of times this path returned 404.",
                        verbose_name="hit count",
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this 404 was first recorded.",
                        verbose_name="first seen at",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this 404 was most recently recorded.",
                        verbose_name="last seen at",
                    ),
                ),
                (
                    "referrers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Top referrers for this 404, as {url: count} pairs.",
                        verbose_name="referrers",
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether a redirect rule has been created for this path.",
                        verbose_name="resolved",
                    ),
                ),
            ],
            options={
                "verbose_name": "404 log entry",
                "verbose_name_plural": "404 log entries",
                "db_table": "icv_sitemaps_redirect_log",
                "ordering": ["-hit_count"],
                "constraints": [
                    models.UniqueConstraint(fields=("path", "tenant_id"), name="icv_sm_rdlog_path_tnt_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="RedirectRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label for this redirect rule.",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("prefix", "Prefix"),
                            ("regex", "Regex"),
                        ],
                        default="exact",
                        help_text="How to match the source pattern against the request path.",
                        max_length=10,
                        verbose_name="match type",
                    ),
                ),
                (
                    "source_pattern",
                    models.CharField(
                        db_index=True,
                        help_text="URL path to match (exact path, prefix, or regex).",
                        max_length=2000,
                        verbose_name="source pattern",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Target URL. Leave blank for 410 Gone responses.",
                        max_length=2000,
                        verbose_name="destination",
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (301, "301 Moved Permanently"),
                            (302, "302 Found"),
                            (307, "307 Temporary Redirect"),
                            (308, "308 Permanent Redirect"),
                            (410, "410 Gone"),
                        ],
                        default=301,
                        help_text="HTTP status code for the redirect response.",
                        verbose_name="status code",
                    ),
                ),
                (
                    "preserve_query_string",
                    models.BooleanField(
                        default=True,
                        help_text="Carry the original query string to the destination URL.",
                        verbose_name="preserve query string",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are not evaluated.",
                        verbose_name="is active",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers are evaluated first.",
                        verbose_name="priority",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is automatically skipped after this time. Null means never expires.",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been matched.",
                        verbose_name="hit count",
                    ),
                ),
                (
                    "last_hit_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this rule last matched a request.",
                        null=True,
                        verbose_name="last hit at",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("auto", "Auto"),
                            ("signal", "Signal"),
                            ("import", "Import"),
                        ],
                        default="admin",
                        help_text="How this rule was created.",
                        max_length=10,
                        verbose_name="source",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Leave blank for single-tenant use.",
                        max_length=200,
                        verbose_name="tenant ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this redirect rule.",
                        verbose_name="notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "redirect rule",
                "verbose_name_plural": "redirect rules",
                "db_table": "icv_sitemaps_redirect_rule",
                "ordering": ["priority", "source_pattern"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "is_active", "priority"],
                        name="icv_sm_rdr_tnt_actv_pri_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("match_type", "exact")),
                        fields=("source_pattern", "tenant_id"),
                        name="icv_sm_rdr_src_tnt_exact_uniq",
                    )
                ],
            },
        ),
    ]
