# Generated by Django 6.0.3 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_sitemaps", "0004_redirectlog_redirectrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitemapsection",
            name="section_type",
            field=models.CharField(
                choices=[("model", "Model"), ("static", "Static")],
                default="model",
                help_text=(
                    'Where this section\'s URLs come from: "model" (a Django queryset) or '
                    '"static" (a declared list or callable in `settings`).'
                ),
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sitemapsection",
            name="model_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    'Django model in "app_label.ModelName" format, e.g. "catalog.Product". '
                    'Required when section_type is "model"; left blank for "static" sections.'
                ),
                max_length=500,
            ),
        ),
    ]
