# Generated by Django 6.1.1 on 2026-09-03 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_sitemaps", "0006_alter_sitemapfile_generated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsentry",
            name="certification_id",
            field=models.CharField(
                blank=True,
                help_text="Optional TAG-ID certification authority ID.",
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field must not contain newline characters.",
                        regex="^[^\\r\\n]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="adsentry",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="Optional comment for internal reference.",
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field must not contain newline characters.",
                        regex="^[^\\r\\n]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="adsentry",
            name="domain",
            field=models.CharField(
                help_text='Advertising system domain, e.g. "google.com".',
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field must not contain newline characters.",
                        regex="^[^\\r\\n]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="adsentry",
            name="publisher_id",
            field=models.CharField(
                help_text="Publisher account ID assigned by the advertising system.",
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field must not contain newline characters.",
                        regex="^[^\\r\\n]*$",
                    )
                ],
            ),
        ),
    ]
