# Generated by Django 6.0.3 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_sitemaps", "0007_ads_entry_newline_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robotsrule",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text=(
                    "Tiebreaker for rules of equal specificity within the user agent "
                    "group (lower = first). Rendering resolves precedence by longest "
                    "path match per RFC 9309; this field does not override that, it "
                    "only orders rules the RFC treats as equally specific."
                ),
            ),
        ),
    ]
