# Generated by hand for icv_sitemaps 3.2.0 (issue #50).
#
# Adds a nullable tenant_ref FK to the six tenant-keyed models, resolved
# from ICV_TENANT_MODEL at migration-generation time (ADR-019 section 2
# fall-through-floor pattern, mirroring icv-email's 0001_initial). Written
# by hand rather than generated via makemigrations, per the brief for issue
# #50.

import django.db.models.deletion
from django.db import migrations, models

from icv_sitemaps.conf import ICV_TENANT_MODEL


class Migration(migrations.Migration):
    dependencies = [
        ("icv_sitemaps", "0008_alter_robotsrule_order"),
        migrations.swappable_dependency(ICV_TENANT_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sitemapsection",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this row belongs to. Optional; when set, tenant_id is derived from it.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to=ICV_TENANT_MODEL,
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="robotsrule",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this row belongs to. Optional; when set, tenant_id is derived from it.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to=ICV_TENANT_MODEL,
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="adsentry",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this row belongs to. Optional; when set, tenant_id is derived from it.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to=ICV_TENANT_MODEL,
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="discoveryfileconfig",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this row belongs to. Optional; when set, tenant_id is derived from it.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to=ICV_TENANT_MODEL,
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="redirectrule",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this row belongs to. Optional; when set, tenant_id is derived from it.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to=ICV_TENANT_MODEL,
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="redirectlog",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this row belongs to. Optional; when set, tenant_id is derived from it.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to=ICV_TENANT_MODEL,
                verbose_name="tenant",
            ),
        ),
    ]
