# Generated by Django 6.0.7 on 2026-09-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_sitemaps", "0009_tenant_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitemapsection",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Section-specific configuration overrides (JSON). Static sections read "url_provider" and "urls"; every section type may override generation limits with "max_urls_per_file", "max_file_size_bytes" and "gzip", falling back to the matching ICV_SITEMAPS_* setting when absent.',
            ),
        ),
    ]
